### ISSUE TITLE
back and forward buttons don't work

### ISSUE THREAD

**Issue by schlichtanders** [vistarsvo/emBrowser4Intellij#2]
everything else seems to work, but not back and forth buttons

installed via Intellij Idea Plugins
**plugin version:** 1.0.1
**Intellij Idea version:**
IntelliJ IDEA 2017.3.5 (Ultimate Edition)
JRE: 1.8.0_152-release-1024-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Operating System: Windows 10 10.0, 64 bit

**Comment by schlichtanders** [comment]
does also not work for

**operating System:** Windows 10, 64bit
**plugin version:** 1.0.1
**Intellij Idea Version:**
IntelliJ IDEA 2018.2 (Ultimate Edition)
Build #IU-182.3684.101, built on July 24, 2018

JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by vistarsvo** [comment]
Fix in #4

**Comment by vistarsvo** [comment]
Please, update plugin to ver 1.1.2 and check is it working now?

**Comment by schlichtanders** [comment]
yes they work!!!
thank you so much for such a fast fix
