### ISSUE TITLE
plus button does not work when max zoom out

### ISSUE THREAD

**Issue by schlichtanders** [vistarsvo/emBrowser4Intellij#3]
if you click the minus button again and again until it is maximally zoomed out, the plus button no longer works (before that it works seamlessly as expected)

**operating System:** Windows 10, 64bit
**plugin version:** 1.0.1
**Intellij Idea Version:**
IntelliJ IDEA 2018.2 (Ultimate Edition)
Build #IU-182.3684.101, built on July 24, 2018

JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by vistarsvo** [comment]
Fix in #4

**Comment by vistarsvo** [comment]
Please, update plugin to ver 1.1.2 and check is it working now?

**Comment by schlichtanders** [comment]
the zooming out now works again
however
- if I clicked the minus button until I reached the end
- now the minus button is greyed out and at the right side "25%" is printed
- and then click on the new "1:1" button to reset the %
- now the minus button is still greyed out

pressing plus button once will enable the minus button again, so in principle the functionality is there already

Thank you very much for fixing these issues so fast!

**Comment by vistarsvo** [comment]
Thank's for feed back. I'll try to fix zoom and update plugin for tomorrow updates :)
